apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-volume-claim
  namespace: hostpath-testing
  labels:
    app: hostpath
spec:
  storageClassName: hostpath-scn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi