apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: hostpath-testing
  labels:
    app.kubernetes.io/name: hostpath-pod
spec:
  containers:
    - name: hostpath-pod
      image: alpine
      args:
      - /bin/sh
      - -c
      - cd /mnt; date > plik.txt; sleep infinity
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      volumeMounts:
            - mountPath: /mnt
              name: hostpath-data
  volumes:
        - name: hostpath-data
          persistentVolumeClaim:
            claimName: hostpath-volume-claim