apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cronjob-volume-claim
  namespace: cronjob-testing
  labels:
    app: cronjob
spec:
  storageClassName: cronjob-scn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi