apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: proxy-test
data:
  nginx.conf: |
    events {}

    http {
      upstream httpbin {
        server httpbin.proxy-test.svc.cluster.local:8000;
      }

      upstream echo {
        server echoserver.proxy-test.svc.cluster.local:80;
      }

      server {
        listen 80;

        location /httpbin/ {
          proxy_pass http://httpbin/;
        }

        location /echo/ {
          proxy_pass http://echo/;
        }

        location /echo {
          proxy_pass http://echo/;
        }
      }
    }
