apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: postgres-testing
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: /data/postgresql